config/routes.rb
Rails.application.routes.draw do
  root "sessions#index"

  #creating a new session, model object(user) has already been created
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  #creating a new model opject so we send the route to the users contoller
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  resources :exercises
  resources :workouts
  resources :workout_plans
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user
  belongs_to :workout
end

app/models/user.rb
class User < ApplicationRecord
  has_many :exercises
  has_many :workout_plans
  has_many :workouts, through: :workout_plans
  #bycrpt gem macro
  has_secure_password

  validates :username, :email, presence: true
  validates :username, :email, uniqueness: true
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :workout_plan
  has_many :exercises
end

app/models/workout_plan.rb
class WorkoutPlan < ApplicationRecord
  belongs_to :user 
  has_many :workouts
  has_many :exercises, through: :workouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
  end

  def new
  end
  
  def create
    #find user from db
    # name="user[email]"
    @user = User.find_by(email: params[:user][:email])

    #if we find user by email and they have the right password
    if @user && @user.authenticate(params[:user][:password])
      #log the user in, remember from one page to another
      session[:user_id] = @user_id
      redirect_to user_path(@user)
    else
      flash[:message] = "Sorry, please try again."
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid? 
      @user.save
      #user has been saved we now want to remeber the user when they go to the next page
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    # "user"=>{"username"=>"corbintest", "email"=>"corbin@test.com", "password"=>"password"}
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/workout_plans_controller.rb
class WorkoutPlansController < ApplicationController
  
  def index
    @workout_plans = current_user.workout_plans
  end

  def show
    @workout_plan = WorkoutPlan.find_by(params[:id])
  end

  def new
    @workout_plan = WorkoutPlan.new
  end

  def create
    # byebug
    # build compared to new adds the newly created workout_plan to the workout_plans collection
    @workout_plan = current_user.workout_plans.build(workout_plan_params)
    if @workout_plan.save
      redirect_to workout_plan_path(@workout_plan)
    else
      render :new
    end
  end

  def edit
    @workout_plan = WorkoutPlan.find_by(id: params[:id])
  end

  def update
    @workout_plan = WorkoutPlan.find_by(id: params[:id])
    if @workout_plan.update(workout_plan_params)
      redirect_to workout_plan_path(@workout_plan)
    else
      render :edit
    end
  end

  private 

  def workout_plan_params
    # "workout_plan"=>{"title"=>"Push, Pull, Legs", "description"=>"This is my favorite workout plan", "active"=>"1"}
    params.require(:workout_plan).permit(:title, :description, :active)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @workout = Workout.new
  end

  def create
    # byebug
  end

  private

  def workout_params
    # workout"=>{"title"=>"Push", "feeling"=>"Strong", "complete"=>"0"}
    params.require(:workout).permit(:title, :feeling, :complete)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end


  def logged_in?
    !!current_user
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workout_plans_helper.rb
module WorkoutPlansHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkoutTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if logged_in? %>
      <%= link_to 'Logout', '/logout', method: :delete%>
      <%= link_to 'My Plans', workout_plans_path %>
      <%= link_to 'Create a Plan', new_workout_plan_path %>
    <% else %>
      <%= link_to 'Login', login_path %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up Here:</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%# required:true does not protect on the backend %>
  <%= f.text_field :username   %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

app/views/workout_plans/_form.html.erb
<%= form_for @workout_plan do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br></br>

  <%= f.label :description %>
  <%= f.text_field :description %>
  <br></br>

  <%= f.label :active %>
  <%= f.check_box :active, default: false  %>

    <br></br>

  <%= f.submit%>

<% end %>

app/views/workout_plans/edit.html.erb
<h1>Edit <%= @workout_plan.title %></h1>

<%= render "form" %>

app/views/workout_plans/index.html.erb
<h1>You're Plans</h1>

<% @workout_plans.each do |plan|%>
  <div>
    <h3><%= link_to plan.title, workout_plan_path(plan) %> </h3>
    <p>Description: <%= plan.description %> |
    Active: <%= plan.active %>  </p>
  </div><br>
<% end %>

app/views/workout_plans/new.html.erb
<h1>Create a new plan</h1>

<%= render "form" %>

app/views/workout_plans/show.html.erb
<h1><%= @workout_plan.title %></h1>

<p><strong>Type:</strong> <%= @workout_plan.description %> </p>
<p> List exercises here </p>

<%= link_to "Edit Plan", edit_workout_plan_path(@workout_plan) %>

app/views/workouts/_form.html.erb
<%= form_for @workout do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br></br>

  <%= f.label :feeling %> 
  <%= f.text_field :feeling %>
  <br></br>

  <%= f.label :complete %>
  <%= f.check_box :complete, default: false  %>


  <%# NEED TO ADD DATETIME %>

    <br></br>

  <%= f.submit%>

<% end %>

app/views/workouts/edit.html.erb
<h1>Edit a workout</h1>
<%= render 'form' %>

app/views/workouts/new.html.erb
<h1>Add a new workout</h1>
<%= render 'form' %>